# Generated by Django 3.1.7 on 2021-04-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=200)),
                ('mobileNumber', models.CharField(max_length=15)),
                ('dateOfBirth', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
    ]
