# Generated by Django 3.1.7 on 2021-04-11 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
        migrations.AddField(
            model_name='userdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
