# Generated by Django 3.1.7 on 2021-04-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210411_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userdata',
        ),
    ]
