# Generated by Django 3.2 on 2021-04-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccoutDetail',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=500)),
                ('role', models.TextField()),
                ('mobileNumber', models.DecimalField(decimal_places=0, default=True, max_digits=10)),
                ('user_dateOfBirth', models.CharField(default=True, max_length=50)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_actived', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
