# Generated by Django 3.2 on 2021-04-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Authentication', '0002_rename_user_id_useraccoutdetail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccoutdetail',
            name='confirm_password',
            field=models.CharField(default=False, max_length=500),
        ),
    ]
