# Generated by Django 3.2 on 2021-04-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System_Authentication', '0003_useraccoutdetail_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccoutdetail',
            name='confirm_password',
        ),
    ]
