# Generated by Django 3.2 on 2021-04-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Authentication', '0004_remove_useraccoutdetail_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpAuthenticationSystem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobileNumber', models.DecimalField(decimal_places=0, default=True, max_digits=10)),
                ('Otp', models.DecimalField(decimal_places=0, default=True, max_digits=10)),
                ('Otp_Created_Count', models.DecimalField(decimal_places=0, default=True, max_digits=4)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
