# Generated by Django 3.2 on 2021-04-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Authentication', '0005_otpauthenticationsystem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpauthenticationsystem',
            old_name='created_date',
            new_name='Firstdate_at',
        ),
        migrations.RenameField(
            model_name='otpauthenticationsystem',
            old_name='updated_at',
            new_name='Lastdate_at',
        ),
        migrations.AddField(
            model_name='otpauthenticationsystem',
            name='user_id',
            field=models.DecimalField(decimal_places=0, default=True, max_digits=5),
        ),
    ]
